[project]
name = "pip-default-package"
version = "0.1.0"
description = "Add your description here"
authors = [
    {name = "MafiaCoconut",email = "alex.kach.2000@gmail.com"}
]
readme = "README.md"
requires-python = ">=3.13.2"
dependencies = [
    "twine (>=6.2.0,<7.0.0)",
    "build (>=1.3.0,<2.0.0)"
]

dependencies = [
    "asyncpg>=0.30.0",
    "pydantic>=2.12.4",
    "sqlalchemy>=2.0.44",
    "custom-package",
]

[tool.poetry]
packages = [{ include = "pip_package_default", from = "src" }]

[tool.uv.sources]
custom-package = { path = "../custom-package", editable = true }

[build-system]
requires = ["poetry-core>=2.0.0,<3.0.0"]
build-backend = "poetry.core.masonry.api"
